version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: visit-tracker-server
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    volumes:
      - server_data:/root/data
    networks:
      - visit-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: visit-tracker-client
    restart: unless-stopped
    ports:
      - "82:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - visit-tracker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  visit-tracker-network:
    driver: bridge

volumes:
  server_data:
    driver: local 